envs:
- key: NODE_ENV
  scope: RUN_AND_BUILD_TIME
  value: production
name: staging-production-management
region: sfo
services:
- dockerfile_path: packages/dashboard-api/Dockerfile
  envs:
  - key: S3_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:0Zu3ic7TA7evwQ6ay4hRXwK4v4Uuu3Cy:1B4P4KHBBPm6eeyWM6cnSWsBLKOMxXmS+qwigpiIOoUc/4TN]
  - key: S3_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:gPr8jfYzxBrDerGWzkgEVsMAzVPgyqSJ:UCkplJzocgl3Phc/ca3bVyBs8tJNL1nGrmOKGN7301/kVw/AEXHR2/IIWqZQ9VrlPUhQzbe04gkaTjQ=]
  - key: MONGO_URI
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:AByLcc/71MLEQxhtfBKS9kJH1pdZkhUj:zO0OO5ya5CXSLkpxAAjZbE+FKqeDyICBNycB4D3bByfdHlTzJ5q55gncAhseHlX1yI8GXGwQU0IwIOADcezumpUSZFuRCu/IiNuK1wB9dxgIocsqeZkcUDH6b+fwxF4=]
  - key: JWT_EXPIRE
    scope: RUN_AND_BUILD_TIME
    value: 5d
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: info
  - key: FIREBASE_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:sll3S9A62BjJ5Rv+bhOyvdkdTkXU9p6j:HzjhrXt0R7pXSjJkoMVqaOR66Lt/8YuW0nohl9FdEKiReD/xi2ljjsrPFRqIVBWRFJaKfXoa3g==]
  - key: FIREBASE_PROJECT_ID
    scope: RUN_AND_BUILD_TIME
    value: projectmanagement-ec889
  - key: FIREBASE_CLIENT_EMAIL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:ILo+Ulo2OfR+gq4fOU3mq/kva0OEj0AJ:BfLwhs4tHxxgI2ieq93z0/c7f0w6+CGR8GVgaMqAA3cKl9p+QKLvKllp1pYz3ROLd3GLKgSjB6KW2KaXTi0rjMztJ8CfoXnbRW+BmsqssxCwSgtNoLK/]
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Ltk3GLoD60bvnmogUh83eqWzbWO6exg7:w9vQjEHwInGBsevz/Oe2sd3AYajDOuZddQ59STsMt7Tuns3OMHl3bHGR7RqrcL72vU9I1Mfohzku2wNCUdNz8VVfeYzQ8nwk+UiyGgBrag53q5VuBuHT/Fq9AuI0n/GMCrMu36sATJZU9XVBHHUGs9Kn2g==]
  - key: FIREBASE_PRIVATE_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:dKH3TSol/BLewfClcZyJPgNSJ6zyP+9m:XMbd3M6KBRBzE96qYp/47as3xqPdw4+XyeNvNwfrBA8fM/H0utAGfnPWo+KldzFhLE3asyESjSTl85ODev1m2O5Ph6VtCU3KYFmcwTpKKMos8BD799r1+OKnBhw879A+1IJy/pyLCKrZ75bDp/NMzQKricShjpGeZfGwa+vlX4w7mtGHSSq+ipyH7jm5KBV4UV31Dt0kF4TodSDHHRbcsVKg0fPKddcsoaQmXIEEVTK2hyryHkdHEgF9sPLFgk9pMXOjiKdP5Hzt2l4U+3FMgO3f0O1GL2Zqo1IzCZcriULU+BHPkukJVWOkn0uHz89sEhXZePLUc2UNNN0TYtuB7PSE8ggJctdNygO4eONdjQB5MOIHot3Rw6XMnp03Sc8idfPSfJkW01F+wG0icyG1IbOaH18JiRgEfn9JmgzjB2Bj0Ux5bgIPL7WkjwdrRSixKUILPWIDRIXT96cgrQkt530CSImpVhVM4gMmuEBms2aTh8+2dW6HHHP4H/PgUH1YBZD/B8iFh4HcUgqeoad1RBYSXYIrwcTOeY9F36ln/YGXRZn1iAEYYwaYP1YwrrQyfX2osTfHF7VRApkiyUEVOFmnVIAQjpl51FmjlCqgTsFPS3+T8NKt8UUqOtS+/APQMDH7f8j6lo2DLnzaVdsKhGO0GM0I6SpOk0jcG21OQuAaj1mTA9OXdJ7V76uiTASZqDCy3nGIFyCmWstPQcdq7kBd7PxPknflYUpvgKYCbuv6zpcT1j6tKiSTANCdE15xCihGPJpNjjSyB+l5PYRXYP6N8KOufwACWTz2PxiinlIGNCBkAN39rMBLKJXbFsVBaLXUMBqBt19ANwuafxd4xoWaU2SLHlteLLHY6H4XW9Mrkj1hghhYqsUDqv6O0nhNfHcVBzmr4/GABeFtUil/kn0PW5zR4zp6bznq5vUkQII1FFfR1VaIIslY9hJ5wauN280bNrCpMCy3C1J3yRwEel5yVVMgpAUHfQFvtIsGZuNKFgVFPeiL/fOD/tDGmPRrZd7Qx72UC01J6iXjLZtrBQEg+mEv7pa0arMDrznZsfHYx13KOUyCQ2G8CnUkf5u7V1s1y5AZlC+iH+Wqu5kd1mDZzNQ6le36lEqOdcoEgdi+Zq4IQjlmv0WvktOSKCiamvrocbzRaDWM5V3X6heG1vmLRtZzHfr7GIic+xM/BMdJBmVKYisMw0xEXxuT1qBf80is0QfS37PVzKMy4U6yagCTW1bRRBg6dkYeyoNBK0Uro8Y8toapl2R+Tt5rK5teQeCP0boXn8K5SXkmSfrVfqj/QxOZycKLlrhxJTit6AbkSQEJXQ8g1bdrE6ew+g+XM7UyaUt+g0gt31OXHNsIP6l4Y/Asyr5NpIkEjFkzjylkBH9VvLdbGlTjLVHltCCvWTg264ndYGtSqNfhaTrmylztdQdE8HP0lre4mP3hZJd3+EilYZcbj7xf981h4WNvKHpBce3qHsvQVZa6zo5LxVQGBbg1BkgZjXvqq0pGMheCKE1zbnP7z9SNOmzyEkW9bVaYsbSKORfhpftwhJyJR2Gclgv3hX+bHVQ09Ib5Khu7fDrpMm/7fE7SIndcrFnxSZjGLkntVo6ECQGGl0C+XaV18GoVj08FkAJ9HEwVNM23QprEErAGzVPAv8JZ0rGmILQ79bCo4bHA/zph/cybmtpO35YSZ7NfhMkt5hUzzQWWK9eceQfEgoqtDDl1UbJuo/CkLYNqSlB8epWAGejm22IYTSSvZEz6kwbkmwlFjAzomsr3jJ38/FCHVUqLZlp5HJNBQt8pLj/lODiBK02iwSu8pmT85hALrxTuQD4yKBTfN8IawKndzvUmOSBnA/ktMXJCTG3TJTzp572jidGDr00OPBJcobrsEu22X3M1VRKKz0mS6ZY6TiwvvmFZaxYPuz2aANUhOOjVn2/rZ9YAg2TLU8+qMC6ka8JwLl5e9vjz5rC/BBv1gCTpEx/Laq8Cl+zuM8Hgg+uV9HTbW6zvpHBzmbxuShKdH1t6tl2gvCDflpgefxR6EL7JG6WE5EAMZtZUUCLJl3UCqYDOoz+AuGm0XGECBhkt6dR/pcnAD2IYP66WqC3I4+3A4OVT7Ks9KEruOJlfc3sFgiVuIFEqZ5lIyWEDDKzN/tvz2Bb9+Y4canuU4PpJENbro2WOEImMvd0OUV3XOmWjkOeiA4z/cqm735MPpLfOsrJeBZTPN1cVCqzig/p5ZGggqu0mpSYCu78OBX4V3nWsyj8x52lgnuy76FcsxTHslr8KfGAISY0MbPKuYB+FTRHjwARLuGi14DEbKbsMVvX9dqsZOQsW4wBdEb2Hyj8lJgrwO3rHMkF8Anm/pqdw/HbVy3AhffUMTnPCNLfvOqxSC7Fs8epZCwneJlwMaWlWRrx8LqT4Wvj4QLtb+iktGTXTMpW0RqBk9xfHdga2jkG4AjYpCgNp59wjUeSVQbhACdI5cUSE1fkp835dDpxRRJt+xX6+BkoSUn/jumO04qzek8itRCozvQJqcKCocWMEm2C8gb4pv9GGBF08itog8LnqcnZ3OaELk4AeH+KwhGtNa32N3y7L+f8QCOj8lT34P1gNGDfbUDLJpPESosHqgAcMcZrK0EY9PWq4tg0kreuuQ8SyIqLgHaFYyPbsQDeO7/NwGEfB3bBeXXECpKpbPyf2pkiFKDNnSK4inUfZ7dTDQ1z6+4+PqYm7oIYUPUEjEgQ6mfJRmoMBH5tTb4Yrkue3mv4VpgjUyLLslKf4lZfHoQUX9X4VLzK7JlumPCAPebetsJVflkFIorz1vkolMadkU/xyCoEikTWbisYfK1v5CpjT6/7pet+CCOEbpWemJ+1O81O5ouyKRvLKXqaLSyEjQmwYER/SfdKGhqYinjveUUShmzzn7XtslGDARBkrnm6fmzgTDiHjfhVz5o4cJ6qyzUq1yZoUx9efnz0A85AcB00v+JUDiWRvBJSVy90+/vHuFvs6JzAOh9VbWlMxJDTJH9qBtU/LfucT3GChYGvciKfUOQvk8SoSU62I44/YKJaKfnq0Fcqep8G4/F4Wlg==]
  github:
    branch: master
    deploy_on_push: true
    repo: brookswcook/production-management
  http_port: 4000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: dashboard-api
  routes:
  - path: /api
  source_dir: /
- dockerfile_path: packages/dashboard-front-end/Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: brookswcook/production-management
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: dashboard-front-end
  routes:
  - path: /
  source_dir: /
