const {
  REACT_APP_APOLLO_SERVER_URI = "http://localhost:4000/graphql",
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID,
  REACT_APP_FIREBASE_PUBLIC_VAPID_KEY,
  NODE_ENV,
  REACT_APP_USE_AUTH_EMULATOR,
  REACT_APP_URI,
} = process.env;

if (
  REACT_APP_URI == null ||
  REACT_APP_FIREBASE_API_KEY == null ||
  REACT_APP_FIREBASE_AUTH_DOMAIN == null ||
  REACT_APP_FIREBASE_PROJECT_ID == null ||
  REACT_APP_FIREBASE_STORAGE_BUCKET == null ||
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID == null ||
  REACT_APP_FIREBASE_APP_ID == null ||
  REACT_APP_FIREBASE_PUBLIC_VAPID_KEY == null
)
  throw new Error("Required env variables are not set");

export const config = {
  apolloURI: REACT_APP_APOLLO_SERVER_URI,
  appURI: REACT_APP_URI,
  firebase: {
    apiKey: REACT_APP_FIREBASE_API_KEY,
    authDomain: REACT_APP_FIREBASE_AUTH_DOMAIN,
    projectId: REACT_APP_FIREBASE_PROJECT_ID,
    storageBucket: REACT_APP_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
    appId: REACT_APP_FIREBASE_APP_ID,
    vapidKey: REACT_APP_FIREBASE_PUBLIC_VAPID_KEY,
  },
  nodeEnv: NODE_ENV,
  enableAuthEmulator: REACT_APP_USE_AUTH_EMULATOR,
};
